import Navbar from "@/components/navbar/Navbar";

export const metadata = {
  title: "Paper Trading",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
